package org.example;
// Generated by Selenium IDE

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  public void setUp() throws InterruptedException {
    System.setProperty("webdriver.chrome.driver", "C:\\Users\\RIN\\Downloads\\chromedriver-win64\\chromedriver-win64\\chromedriver.exe");
    driver = new ChromeDriver();
    Thread.sleep(5000);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  public void tearDown() {
    driver.quit();
  }

  public void search() {
    driver.get("https://violet.vn/?fbclid=IwAR2tqq57f4zCDJ5kHI8HfOlyNvFm2f17mrGjCRNZktQQg9zsehwjVGBX_2o");
    driver.manage().window().setSize(new Dimension(784, 912));
    driver.findElement(By.id("search-input")).click();
    driver.findElement(By.id("11")).click();
    driver.findElement(By.id("11")).click();
    driver.findElement(By.id("5")).click();
    driver.findElement(By.cssSelector(".over img")).click();
    js.executeScript("window.scrollTo(0,10.399999618530273)");
  }
  public static void main(String[] args) throws InterruptedException {
    SearchTest test = new SearchTest();
    test.setUp();
    test.search();
    test.tearDown();
  }
}
